# head
menu:
  Home: /blog/
  Archives: /blog/archives
rss: /blog/rss.xml
favicon: /favicon.png

# main
date_format: 'MMMM Do, YYYY'
excerpt_link: READ MORE
comment_link: 0 COMMENTS

# foot
# themes_mata: ' ❤ Theme by <a href="http://unmric.com" target="_blank">unmric</a>'
google_analytics: UA-71967747-2

